"""Generate ``metadata/provenance.json``.

Records every source the v1 baseline draws from, with role, retrieval URL,
and SHA-256 where available. Designed to be deterministic across reruns:
no wall-clock timestamps, no machine-specific paths. Re-generated by
``uv run indlaw build-provenance``.

Schema (v1):

    {
      "schema_version": "1",
      "sources": [
        {
          "id": "<short stable identifier>",
          "kind": "scraper" | "manual-transcription" | "offline-html" | "scout",
          "name": "<human-readable>",
          "role": "<how the v1 baseline uses this>",
          "url": "<canonical landing URL>",
          "discovered_via": "<sitemap/index URL when applicable>",
          "file_path": "<relative path within the repo, when applicable>",
          "sha256": "<hex>",
          "retrieved": "YYYY-MM-DD",
          "stats": { ... }
        }
      ]
    }
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_PATH = REPO_ROOT / "metadata" / "provenance.json"


def _file_sha256(path: Path) -> str | None:
    if not path.exists():
        return None
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _scraped_count(rel_dir: str, glob: str = "*.json") -> int:
    p = REPO_ROOT / rel_dir
    if not p.exists():
        return 0
    return sum(1 for _ in p.glob(glob))


def _manuscript_articles() -> list[str]:
    src = REPO_ROOT / "pipeline" / "sources" / "manuscript"
    if not src.exists():
        return []
    return sorted(p.stem for p in src.glob("article-*.txt"))


def _manuscript_schedules() -> list[str]:
    src = REPO_ROOT / "pipeline" / "sources" / "manuscript"
    if not src.exists():
        return []
    return sorted(p.stem for p in src.glob("schedule-*.txt"))


def build() -> int:
    """Write ``metadata/provenance.json``. Returns the number of sources."""
    sources: list[dict] = []

    sources.append({
        "id": "clpr-articles",
        "kind": "scraper",
        "name": "Centre for Law and Policy Research — per-article URLs",
        "role": "primary baseline (1950) — 389 articles",
        "url": "https://www.constitutionofindia.net/",
        "discovered_via": "https://www.constitutionofindia.net/articles-sitemap.xml",
        "retrieved": "2026-05-07",
        "stats": {
            "sitemap_url_count": 495,
            "articles_emitted": _scraped_count("pipeline/intermediate/scraped/articles"),
        },
        "notes": (
            "Per-article pages parsed for the Version 2 (Constitution of India 1950) "
            "block; letter-suffixed slugs are excluded from the baseline as they are "
            "post-1950 insertions. CLPR labelling occasionally drifts (heading number "
            "≠ slug number); the slug is treated as authoritative."
        ),
    })

    sources.append({
        "id": "clpr-schedules",
        "kind": "scraper",
        "name": "Centre for Law and Policy Research — per-schedule URLs",
        "role": "primary baseline (1950) — Schedules 1–8 (parts merged)",
        "url": "https://www.constitutionofindia.net/",
        "discovered_via": "https://www.constitutionofindia.net/schedules-sitemap.xml",
        "retrieved": "2026-05-08",
        "stats": {
            "sitemap_url_count": 21,
            "segments_emitted": _scraped_count("pipeline/intermediate/scraped/clpr-schedules"),
        },
        "notes": (
            "8 baseline schedules sourced; post-1950 9th/10th/11th/12th excluded. "
            "Schedule 7 List III was filled from the manuscript because CLPR carries "
            "only the post-1976 consolidated form."
        ),
    })

    manuscript_pdf = REPO_ROOT / "docs" / "Original-Manuscript-of-the-Constitution-of-India_New1.pdf"
    sources.append({
        "id": "manuscript",
        "kind": "manual-transcription",
        "name": "Lok Sabha calligraphic manuscript of the Constitution of India",
        "role": (
            "primary baseline fill (6 articles, 2 schedule sub-parts) + spot-check "
            "ground truth (5 articles)"
        ),
        "url": "https://www.constitutionofindia.net/read/original-manuscript/",
        "file_path": "docs/Original-Manuscript-of-the-Constitution-of-India_New1.pdf",
        "sha256": _file_sha256(manuscript_pdf),
        "retrieved": "2026-05-07",
        "stats": {
            "articles_transcribed": _manuscript_articles(),
            "schedules_transcribed": _manuscript_schedules(),
        },
        "notes": (
            "The signed-as-adopted 26 January 1950 copy, calligraphed by Prem Behari "
            "Narain Raizada. Most authoritative 1950 text the project draws on. The "
            "PDF itself is not committed (gitignored due to size); the SHA-256 here "
            "lets contributors verify they hold the same artifact."
        ),
    })

    ik_html = REPO_ROOT / "docs" / "ConstitutionofIndia_IK.html"
    sources.append({
        "id": "ik",
        "kind": "offline-html",
        "name": "Indian Kanoon — Constitution of India (offline save)",
        "role": (
            "cross-check + Phase 2 amendment metadata seed (95 distinct amendment-act "
            "citations harvested across 163 articles)"
        ),
        "url": "https://indiankanoon.org/doc/237570/",
        "file_path": "docs/ConstitutionofIndia_IK.html",
        "sha256": _file_sha256(ik_html),
        "retrieved": "2026-05-08",
        "stats": {
            "articles_extracted": _scraped_count("pipeline/intermediate/scraped/ik"),
        },
        "notes": (
            "Akoma Ntoso–styled HTML. Carries the *current* consolidated Constitution "
            "with inline akn-remark editorial annotations citing amending acts. NOT a "
            "1950 baseline source — useful for cross-checking unchanged-since-1950 "
            "articles, filling the unchanged subset of gaps, and seeding Phase 2."
        ),
    })

    bareacts_url = "https://www.bareactslive.com/ACA/ACT401.HTM"
    sources.append({
        "id": "bareactslive",
        "kind": "scout",
        "name": "Bare Acts Live — Constitution of India",
        "role": "scouting; future HEAD-state verification candidate",
        "url": bareacts_url,
        "retrieved": "2026-05-08",
        "notes": (
            "Current consolidated text with bracketed amendment annotations "
            "(`[X]` for inserted text, `[* * *]` for omitted text). Less complete "
            "than IK at the article level (361/395 bare-numeric articles present), "
            "but the bracketed annotations are useful for amendment-history work."
        ),
    })

    ia_pdf = REPO_ROOT / "docs" / "constitutionofin_1ed_1950.pdf"
    ia_txt = REPO_ROOT / "docs" / "constitutionofin_1ed_fulltext.txt"
    sources.append({
        "id": "ia-aggarawala-1950",
        "kind": "scout",
        "name": "Internet Archive — Aggarawala & Aiyar, 'The Constitution of India' (1950 commentary)",
        "role": "scouting (initially mistaken for the 1950 official text)",
        "url": "https://archive.org/details/constitutionofin029189mbp",
        "file_path": "docs/constitutionofin_1ed_1950.pdf",
        "sha256": _file_sha256(ia_pdf),
        "fulltext_path": "docs/constitutionofin_1ed_fulltext.txt",
        "fulltext_sha256": _file_sha256(ia_txt),
        "retrieved": "2026-05-07",
        "notes": (
            "A 1950 *commentary* by Om Prakash Aggarawala and S.K. Aiyar (Rajkamal "
            "Publications / Metropolitan Book Co., Delhi) — NOT the official "
            "Government of India publication. Discovered during Phase 1 scouting; "
            "the constitutional articles are quoted within the OCR'd commentary "
            "but the text is interleaved with extensive editorial notes and the "
            "OCR is noisy. Could still serve as a fallback for future gap fills."
        ),
    })

    out = {
        "schema_version": "1",
        "sources": sources,
    }
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n")
    return len(sources)
